name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v2
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: mariamkhaled/webapp
        dockerfile: Market-Web-Application/Dockerfile
        tags: latest
